{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute'}

{* Type. *}
<div class="block">
    <label>{'Type'|i18n( 'design/standard/content/datatype' )}:</label>
    <p>
    {* Display Audio Plugin Type *}
    {if $attribute.contentclass_attribute.data_text1|ne('')}
    	{ezini($attribute.contentclass_attribute.data_text1, 'TitleText', 'opaudioplayer.ini')|i18n( 'design/standard/class/datatype/ezaudio' )}
	    </p>
	    <label>{'Audio player'|i18n( 'design/standard/class/datatype/ezaudio' )}:</label>
		<p>
		<select name="{$attribute_base}_data_audioplayer_type_{$attribute.id}">
		{foreach ezini($attribute.contentclass_attribute.data_text1, 'PlayerTypes', 'opaudioplayer.ini') as $audioplayertype}
		    <option value="{$audioplayertype}" {if eq( $attribute.content.controls, $audioplayertype )}selected="selected"{/if}>{$audioplayertype|i18n( 'design/standard/class/datatype/ezaudio' )}</option>
		{/foreach}
		</select>
    {else}
        {'Unknown'|i18n( 'design/standard/content/datatype' )}
    {/if}
    </p>
</div>
{/if}

{* Current file. *}
<div class="block">
<label>{'Current file'|i18n( 'design/standard/content/datatype' )}:</label>
{if $attribute.content.filename}
<table class="list" cellspacing="0">
<tr>
    <th>{'Filename'|i18n( 'design/standard/content/datatype' )}</th>
    <th>{'MIME type'|i18n( 'design/standard/content/datatype' )}</th>
    <th>{'Size'|i18n( 'design/standard/content/datatype' )}</th>
</tr>
<tr>
    <td>{$attribute.content.original_filename}</td>
    <td>{$attribute.content.mime_type}</td>
    <td>{$attribute.content.filesize|si( byte )}</td>
</tr>
</table>
{else}
<p>{'There is no file.'|i18n( 'design/standard/content/datatype' )}</p>
{/if}
</div>

{* Remove button. *}
{if $attribute.content.filename}
    <input class="button" type="submit" name="CustomActionButton[{$attribute.id}_delete_media]" value="{'Remove'|i18n('design/standard/content/datatype')}" title="{'Remove the file from this draft.'|i18n( 'design/standard/content/datatype' )}" />
{else}
    <input class="button-disabled" type="submit" name="CustomActionButton[{$attribute.id}_delete_media]" value="{'Remove'|i18n('design/standard/content/datatype')}" disabled="disabled" />
{/if}

<div class="block">
    <input type="hidden" name="MAX_FILE_SIZE" value="{$attribute.contentclass_attribute.data_int1|mul( 1024, 1024 )}" />
    <label for="{$attribute_base}_media_{$attribute.id}_file">{'New file for upload'|i18n( 'design/standard/content/datatype' )}:</label>
    <input class="box" id="{$attribute_base}_media_{$attribute.id}_file" name="{$attribute_base}_data_mediafilename_{$attribute.id}" type="file" />
</div>

<div class="block">

<div class="element">
    <label for="{$attribute_base}_media_{$attribute.id}_autoplay">{'Autoplay'|i18n( 'design/standard/content/datatype' )}:</label>
    <input type="checkbox" id="{$attribute_base}_media_{$attribute.id}_autoplay" name="{$attribute_base}_data_media_is_autoplay_{$attribute.id}" value="1" {if $attribute.content.is_autoplay}checked="checked"{/if} />
</div>

<div class="element">
    <label for="{$attribute_base}_media_{$attribute.id}_loop">{'Loop'|i18n( 'design/standard/content/datatype' )}:</label>
    <input type="checkbox" id="{$attribute_base}_media_{$attribute.id}_loop" name="{$attribute_base}_data_media_is_loop_{$attribute.id}" value="1" {if $attribute.content.is_loop}checked="checked"{/if} />
</div>

<div class="break"></div>
</div>

{/default}
