{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if $attribute.content.filename}
    {if $attribute.contentclass_attribute.data_text1|ne('') }
    	{if and( $attribute.contentclass_attribute.data_text1|downcase()|ne('dewplayer'), $attribute.content.controls|ne('') ) }
    		{include uri=concat('design:content/datatype/view/ezaudio/', $attribute.contentclass_attribute.data_text1|downcase(), '_', $attribute.content.controls|downcase(), '.tpl') attribute=$attribute plugin_path=ezini($attribute.contentclass_attribute.data_text1, 'PluginPath', 'opaudioplayer.ini')}
    	{else}
    	    {include uri=concat('design:content/datatype/view/ezaudio/', $attribute.contentclass_attribute.data_text1|downcase(), '_basic.tpl') attribute=$attribute plugin_path=ezini($attribute.contentclass_attribute.data_text1, 'PluginPath', 'opaudioplayer.ini')}
    	{/if}
    {else}
        {'Unknown'|i18n( 'design/standard/content/datatype' )}
    {/if}
{else}
    {'No audio file is available.'|i18n( 'design/standard/content/datatype' )}
{/if}
