{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
<label>{'Audio player type'|i18n( 'design/standard/class/datatype/ezaudio' )}:</label>
<select name="ContentClass_ezaudio_type_{$class_attribute.id}">
{foreach ezini('AudioPlayers', 'AudioPlayersTypes', 'opaudioplayer.ini') as $audioplayerstype}
    <option value="{$audioplayerstype}" {if eq( $class_attribute.data_text1, $audioplayerstype )}selected="selected"{/if}>{ezini($audioplayerstype, 'TitleText', 'opaudioplayer.ini')|i18n( 'design/standard/class/datatype/ezaudio' )}</option>
{/foreach}
</select>
</div>

<div class="block">
<label>{'Max file size'|i18n( 'design/standard/class/datatype' )}:</label>
<input type="text" name="ContentClass_ezmedia_max_filesize_{$class_attribute.id}" value="{$class_attribute.data_int1}" size="5" maxlength="5" />&nbsp;MB
</div>


